---
name: Generate Atlases
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Atlases
        run: make data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: actions/generate-atlases
          commit-message:  Regenerate atlas databases
          delete-branch: true
          title: Automated regeneration of atlas databases
          body: Automated regeneration of atlas databases.
          author: GitHub <noreply@github.com>
          reviewers: Meorawr
