---
name: Generate Atlases
on:
  schedule:
    - cron: '0 18 * * *'

  workflow_dispatch:
    inputs:
      mainline_product:
        description: 'Mainline product branch'
        required: true
        default: 'wow'
        type: choice
        options:
          - wow
          - wowt
          - wowxptr
          - wow_beta

      mainline_beta_product:
        description: 'Mainline beta product branch'
        required: false
        default: wow_beta
        type: choice
        options:
          - wow_beta

      classic_product:
        description: 'Classic product branch'
        required: true
        default: 'wow_classic'
        type: choice
        options:
          - wow_classic
          - wow_classic_ptr
          - wow_classic_beta

      classic_era_product:
        description: 'Classic Era product branch'
        required: true
        default: 'wow_classic_era'
        type: choice
        options:
          - wow_classic_era
          - wow_classic_era_ptr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Atlases
        run: make ${MAINLINE_PRODUCT} ${MAINLINE_BETA_PRODUCT} ${CLASSIC_PRODUCT} ${CLASSIC_ERA_PRODUCT}
        env:
          MAINLINE_PRODUCT: ${{ inputs.mainline_product }}
          MAINLINE_BETA_PRODUCT: ${{ inputs.mainline_beta_product }}
          CLASSIC_PRODUCT: ${{ inputs.classic_product }}
          CLASSIC_ERA_PRODUCT: ${{ inputs.classic_era_product }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: actions/generate-atlases
          commit-message:  Regenerate atlas databases
          delete-branch: true
          title: Automated regeneration of atlas databases
          body: Automated regeneration of atlas databases.
          author: GitHub <noreply@github.com>
          reviewers: Meorawr
